set(_agents "${AXTP_CPP_RUNTIME_ROOT}/AGENTS.md")
set(_readme "${AXTP_CPP_RUNTIME_ROOT}/README.md")
set(_boundary "${AXTP_CPP_RUNTIME_ROOT}/docs/LAYER_BOUNDARIES.md")

foreach(_path IN ITEMS "${_agents}" "${_readme}" "${_boundary}")
    if(NOT EXISTS "${_path}")
        message(FATAL_ERROR "Required layer-boundary document is missing: ${_path}")
    endif()
endforeach()

file(READ "${_agents}" _agents_text)
file(READ "${_readme}" _readme_text)
file(READ "${_boundary}" _boundary_text)

if(NOT _agents_text MATCHES "docs/LAYER_BOUNDARIES.md")
    message(FATAL_ERROR "AGENTS.md must require the layer-boundary document before code changes")
endif()
if(NOT _readme_text MATCHES "docs/LAYER_BOUNDARIES.md")
    message(FATAL_ERROR "README.md must link the layer-boundary document")
endif()
if(NOT _boundary_text MATCHES "NearCast product host -> Axent protocol bus -> axtp-cpp-runtime")
    message(FATAL_ERROR "Layer-boundary dependency direction is missing")
endif()
if(NOT _boundary_text MATCHES "must never depend on Axent or NearCast")
    message(FATAL_ERROR "Runtime upper-layer dependency prohibition is missing")
endif()
